-  hosts: all
   remote_user: ec2-user
   become: yes
   tasks:
   - name: Install the latest version of pythonpip
     yum:
        name: python-pip
        state: latest    
   - name: Install the latest version of docker
     yum:
       name: docker
       state: present
   - name: Install the latest version of docker-py
     yum:
       name: python-docker
       state: present
   - name: Create a docker container
     docker_container:
        name: tomcat_deploy
        image: myimage
        state: started
        published_ports:
          - 0.0.0.0:9090:8080
        
