-  hosts: all
   remote_user: ec2-user
   become: yes
   tasks:
   - name: Install the latest version of pythonpip
     yum:
        name: python-pip
        state: latest    
   - name: Install the latest version of docker
     yum:
       name: docker
       state: present
   - name: Start service httpd, if not started
     service:
        name: docker
        state: started
        enabled: yes
   - name: install docker-py module
     pip:
        name: docker-py
        state: present
   - name: Create a docker container
     docker_container:
        name: tomcat_deploy
        image: nj2497/myimage:latest
        state: present
        published_ports:
          - 0.0.0.0:8080:8080
        
